stages:
  load_data:
    cmd: python src/pipeline/01_load_data.py
    deps:
      - src/pipeline/01_load_data.py      
      - ${data.raw_path}
    params:
      - features.datetime_column
      - data.raw_path
      - data.interim_loaded
    outs:
      - ${data.interim_loaded}

  explore_data:
    cmd: python src/pipeline/02_explore_data.py
    deps:
      - src/pipeline/02_explore_data.py      
      - ${data.interim_loaded}
    params:
      - reports.eda_dir
      - eda.sample_rows
    outs:
      - ${reports.eda_dir}

  preprocess_data:
    cmd: python src/pipeline/03_preprocess_data.py
    deps:
      - src/pipeline/03_preprocess_data.py      
      - ${data.interim_loaded}
    params:
      - features.datetime_column
      - features.target.preferred
      - features.lags
      - split.test_size
      - split.random_state
      - data.train
      - data.test
    outs:
      - ${data.train}
      - ${data.test}

  train_model:
    cmd: python src/pipeline/04_train_model.py
    deps:
      - src/pipeline/04_train_model.py      
      - ${data.train}
    params:
      - features.target.preferred
      - model.path
      - model.rf_params
    outs:
      - ${model.path}

  evaluate_model:
    cmd: python src/pipeline/05_evaluate_model.py
    deps:
      - src/pipeline/05_evaluate_model.py      
      - ${data.test}
      - ${model.path}
    params:
      - features.target.preferred
      - metrics.path
      - reports.figures_dir
    outs:
      - ${reports.figures_dir}
    metrics:
      - ${metrics.path}:
          cache: false