data:
  raw_modified: data/raw/power_tetouan_city_modified.csv  
features:
  datetime_column: DateTime
  target:
    preferred: Zone 1 Power Consumption
    alternatives:
    - Zone 2  Power Consumption
    - Zone 3  Power Consumption
  time_parts: true
  lags:
  - 1
  - 24
split:
  test_size: 0.2
  time_ordered: true
models:
  ridge:
    alpha: 1.0
  random_forest:
    n_estimators: 200
    random_state: 42
    n_jobs: -1
