data:
  source: file
  raw_path: data/raw/power_tetouan_city_modified.csv
  interim_loaded: data/interim/loaded.parquet
  train: data/processed/train.parquet
  test: data/processed/test.parquet
  cleaned: data/processed/cleaned_sample.parquet

features:
  datetime_column: datetime
  target:
    # Selecciona la zona objetivo (ej.: "Zone 1", "Zone 2" o "Zone 3")
    preferred: zone_1_power_consumption
    alternatives:
    - zone_2_power_consumption
    - zone_3_power_consumption
  # Lags en pasos (si tus datos son horarios: 1, 24, 168 ~ 1h, 1d, 7d)
  lags: [1, 24, 168]

split:
  test_size: 0.3
  random_state: 42

eda:
  sample_rows: 5

model:
  path: models/power_tetouan_model.pkl
  model_params:
    n_estimators: 800
    learning_rate: 0.05
    max_depth: 6
    min_child_weight: 3
    subsample: 0.8
    colsample_bytree: 0.8
    gamma: 0.1
    reg_lambda: 1.0
    reg_alpha: 0.1
    random_state: 42
    objective: 'reg:squarederror'    
    n_jobs: -1

mlfow:
  tracking_uri: http://localhost:5000 
  experiment_name: TetouanCityPower
  run_name: TetouanPowerModel    

metrics:
  path: metrics/metrics.json

reports:
  eda_dir: reports/eda
  figures_dir: reports/figures